select * from customer limit 20

--Q1. What is the total revenue generated by male vd female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q2 Which customer used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3 Which are the top 5 products with the highest average review rating
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4 Compare the average Purchase Amounts between standard and express shipping
select shipping_type, round(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type 

--Q5 Do subscribed customer spend more ?compare average spend and total revenure
--between subscribers and non-subscribers.
select subscription_status, purchase_amount
COUNT(customer_id) as total cusot
where subscription_status = 'Yes' and avg(purchase_amount)